// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfvJ3MO2ztLxKd0OSSrLItXz2XWxayxY',
    appId: '1:365850429873:web:23a0aca597592ebe765590',
    messagingSenderId: '365850429873',
    projectId: 'private-feed-e2b47',
    authDomain: 'private-feed-e2b47.firebaseapp.com',
    storageBucket: 'private-feed-e2b47.appspot.com',
    measurementId: 'G-ZPY24S6LNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbp3k99lTkatKJ1O2Zc5oOPFPeRU2QjrQ',
    appId: '1:365850429873:android:cb082340f9104b46765590',
    messagingSenderId: '365850429873',
    projectId: 'private-feed-e2b47',
    storageBucket: 'private-feed-e2b47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-5EdAw_wdMYf2Nd-cp9CVFSunqFTHC8',
    appId: '1:365850429873:ios:869122fb97c9c18d765590',
    messagingSenderId: '365850429873',
    projectId: 'private-feed-e2b47',
    storageBucket: 'private-feed-e2b47.appspot.com',
    iosClientId: '365850429873-0tn699vjg9vj53p8nht01um4bh5nhj3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.privateFeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg-5EdAw_wdMYf2Nd-cp9CVFSunqFTHC8',
    appId: '1:365850429873:ios:869122fb97c9c18d765590',
    messagingSenderId: '365850429873',
    projectId: 'private-feed-e2b47',
    storageBucket: 'private-feed-e2b47.appspot.com',
    iosClientId: '365850429873-0tn699vjg9vj53p8nht01um4bh5nhj3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.privateFeed',
  );
}
